### ISSUE TITLE
Release vision_msgs to ROS Eloquent?

### ISSUE THREAD

**Issue by sloretz** [Kukanani/vision_msgs_proposal#34]
Mind releasing vision_msgs to ROS Eloquent? I'd like to release a package that uses it.

**Comment by Kukanani** [comment]
Sure, I should be able to get to this some time this week.

**Comment by Kukanani** [comment]
https://github.com/ros/rosdistro/pull/23697

Been a while since I've done a bloom, hopefully I got everything right with ROS2.
