### ISSUE TITLE
Inconsistent detection ID type between development and release branch

### ISSUE THREAD

**Issue by alsora** [Kukanani/vision_msgs_proposal#38]
Hi,

in this repo he detection ID type has been updated from int to string approximately 1 year ago.
However, this change has never been propagated to the ROS 2 releases.

See https://github.com/alsora/ros2-tensorflow/issues/2

Is there a reason for that?
Could this be addressed in a new foxy release?

Thank you

**Comment by Kukanani** [comment]
Hi, thanks for pointing this out. I definitely want to address this. It will probably result in a major version bump since it will break backwards compatibility.

**Comment by alsora** [comment]
Thank you for the quick fix!
