### ISSUE TITLE
Interest in moving this to be official vision_msgs in ros-perception org?

### ISSUE THREAD

**Issue by SteveMacenski** [Kukanani/vision_msgs_proposal#41]
Hi,

I see this package being used as a standard interface for detection / AI models in ROS. It would be great if this was more "official" then as a `ros-perception/vision_msgs` package so that it can be "official" vision interfaces for ROS. I have the permissions required to help make this happen if you like!

Steve

**Comment by mintar** [comment]
I fully agree, that would be a great idea! I probably don't have to tell you this, but make sure to actually *move* the repo, not fork/copy it. That way, all the links (and even git clone) will keep working with the old URL (GitHub does a HTTP redirect).

**Comment by Kukanani** [comment]
Hi Steve,

I fully support moving this package to `ros-perception`. The only reason it didn't get created there originally was that we weren't sure how much community adoption it would see.

**Comment by SteveMacenski** [comment]
Awesome! I think the easiest way to handle this is the following
- Transfer the repo to me, since you don't have admin on `ros-perception`
- I'll transfer it to `ros-perception`. I'm not sure what all happens with settings in that case, so I'll make sure you still have admin over there in case it removes it for some reason

**Comment by Kukanani** [comment]
Sounds good. Transfer initiated.

**Comment by SteveMacenski** [comment]
I see the request, github says it might take a bit to get over to my side so I can move it to `ros-perception`. Hopefully should happen tonight, if not over the weekend. I'll follow back here when its done.

**Comment by SteveMacenski** [comment]
![image](https://user-images.githubusercontent.com/14944147/101229364-b82c5d00-3654-11eb-9500-0dd2302c7cd3.png)

Well this is truly unique. Its on my account but no `settings` icon for me to move it around... mhm maybe takes a bit for all the permissions to update? Do you still see the settings icon? If so, might be good to add me as an admin in case there's a difference between ownership and permissions.

**Comment by Kukanani** [comment]
What have you done to my repository? 😛 
![image](https://user-images.githubusercontent.com/6893343/101229446-f7af7500-3665-11eb-95a9-1e8b9c394bc0.png)

**Comment by SteveMacenski** [comment]
It'll all work itself out, don't worry :smile: I have no interest in keeping it. If anything else, I'll email someone at GitHub on Monday. They're usually pretty good about working through issues like this quickly. This isn't the first time I've done the "repo-shuffle" to move things into `ros-*`, but first time it didn't automatically give me a `settings` panel...

**Comment by Kukanani** [comment]
Sounds good! Hopefully there are just some database updates that need to propagate around. Please keep me posted.

**Comment by SteveMacenski** [comment]
Nothing changed now on Monday, I contacted GitHub for support.

**Comment by SteveMacenski** [comment]
https://github.com/ros-perception/vision_msgs

Now on `ros-perception`!
