### ISSUE TITLE
Switch default branch to noetic-devel

### ISSUE THREAD

**Issue by mintar** [Kukanani/vision_msgs_proposal#45]
The default branch is still kinetic-devel. Since kinetic is EOL in 4 months, we should switch to noetic-devel.

**Comment by Kukanani** [comment]
I fully support this.

**Comment by SteveMacenski** [comment]
Agreed. Working on getting the settings panel back

(... again :smile:)

**Comment by SteveMacenski** [comment]
Done, thanks for the note!
