### ISSUE TITLE
ObjectHypothesisWithPose array

### ISSUE THREAD

**Issue by dorkamotorka** [Kukanani/vision_msgs_proposal#46]
Why is there no array for ObjectHypotesisWithPose? I understand anybody can do it themselve, but this doesn't add it to ROS standard msgs.

**Comment by mintar** [comment]
`ObjectHypothesisWithPose` is intended to always be used inside a `Detection2D` or `Detection3D` message.

You could say that `Detection2D`/`Detection3D` *are* arrays of `ObjectHypotesisWithPose`, plus some other useful information (header, bbox, source data and tracking id).

**Comment by SteveMacenski** [comment]
But this ticket does bring up a good point that maybe that's context we can put into the msg as a comment

**Comment by Kukanani** [comment]
Closed by #46
@tp4348 feel free to re-open if this doesn't address your needs.
