### ISSUE TITLE
Rolling Release

### ISSUE THREAD

**Issue by lukicdarkoo** [Kukanani/vision_msgs_proposal#55]
Are there any plans on releasing this package to Rolling?

**Comment by Kukanani** [comment]
Sure thing. I’ll look into it on Monday. Thanks for the ping!

**Comment by Kukanani** [comment]
I released to rolling, but was unable to get `bloom` to automatically create the PR in `rosdistro` after several tries.

https://github.com/Kukanani/vision_msgs-release

I keep getting various 403 errors, such as the following:
```
Aborting pull request: HTTP Error 403: Forbidden (https://api.github.com/repos/ros/rosdistro/forks): None
```

I'm not really interested in filling out the lengthy rosdistro PR template myself, and more generally I'd like to get this problem resolved on my machine. @SteveMacenski any tips? My personal access token has full repo and workflow access.

**Comment by SteveMacenski** [comment]
I don’t know, haven’t seen that before

**Comment by Kukanani** [comment]
Tracking the problem at https://github.com/ros-infrastructure/bloom/issues/632. If there are no updates there for a few days I'll make the PR manually.

**Comment by SteveMacenski** [comment]
Opening the PR is the last step, so it should be ready to go with a body block to just copy paste in if that was the only issue

**Comment by Kukanani** [comment]
https://github.com/ros/rosdistro/pull/29188
