### ISSUE TITLE
Release for ROS2 Galactic

### ISSUE THREAD

**Issue by khaghanijavad** [Kukanani/vision_msgs_proposal#61]
Hi, 

Thank you for your package. 

I need this package as a dependency for installing yolo-darknet detection in ROS2-Galactic. 
However, I could not find "vision_msgs" for ROS2-Galactic. Seems there was a discussion on this in #55 & #59, but I could not solve the problem.  
Could you please share (a link to the) implementation of your package for ROS2? 
Thanks.

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/pull/30278

It already is in galactic
