### ISSUE TITLE
About catkin_make question

### ISSUE THREAD

**Issue by ferrari700** [Kukanani/vision_msgs_proposal#62]
Hello, I am sorry to disturb you. The following error occurred when I used catkin_make in a workspace. I am sure that there is a vision_msgs folder in my src folder. How should I solve it? Thank you so much!
![Selection_017](https://user-images.githubusercontent.com/72401926/145662754-2ad38196-c92e-4491-95ca-b69afbf7793f.jpg)

**Comment by s-sarahSM** [comment]
@Kukanani 
I have the same problem mentionned by @ferrari700 
I am working on Nvidia jetson AGX Xavier , ROS Melodic and Ubuntu 18.04
Thank you if you can help

**Comment by Kukanani** [comment]
Hello, please provide steps to produce a minimal working example, ideally using a docker container.

**Comment by igillespie** [comment]
Just a reminder to clone the relative branch, I'm on ros2-galactic, so I used 
`git clone https://github.com/ros-perception/vision_msgs.git -b galactic` 
It compiled fine. I made the mistake of not specifying the branch the first time and had build issues.
