### ISSUE TITLE
Improper use of Pose2D datatype in BoundingBox2D

### ISSUE THREAD

**Issue by tfoote** [Kukanani/vision_msgs_proposal#65]
The semantic definition of Pose2D datatype represents metric position in meters (As per the default units [REP 103](https://www.ros.org/reps/rep-0103.html)) while the BoundingBox2D says that it's in pixels. 

https://github.com/ros-perception/vision_msgs/blob/ef04cafde553780569bb53f0d0bd3d0edc04bfc4/msg/BoundingBox2D.msg#L7-L8

This should not be redefining the units in an established submessage. And furthermore the Pose2D message is deprecated thus should not be being used. 

A pixel space representation of this should be created. It could have the same payload. And even the same message name in `vision_msgs` namespace. Ala `vision_msgs/Pose2D.msg` but with the units appropriately defined as pixels instead of meters. 

Also the axes and direction of the angle should be defined. There are a couple common but different conventions in image space.

**Comment by SteveMacenski** [comment]
Seems reasonable to me. @ijnek can you update your PR in guidance with this instead? https://github.com/ros-perception/vision_msgs/pull/64
