### ISSUE TITLE
Suggestion for new msg type: vision_msgs/Point

### ISSUE THREAD

**Issue by ijnek** [Kukanani/vision_msgs_proposal#66]
Along with the changes in https://github.com/ros-perception/vision_msgs/pull/64, I want to suggest separating the position (x, y) from `vision_msgs/Pose` into a new msg `vision_msgs/Position`.

Often, there are cases where I want to store a point in an image (where heading doesn't make sense), and there is no appropriate message type for it. vision_msgs seems like the appropriate place for this sort of msg.

This is similar to how `position` is a field in [geometry_msgs/Pose.msg](https://github.com/ros2/common_interfaces/blob/master/geometry_msgs/msg/Pose.msg)

**Comment by SteveMacenski** [comment]
Seems reasonable to me if you update all the appropriate locations
