### ISSUE TITLE
BoundingBox2DArray doesn't exist in noetic release (apt)

### ISSUE THREAD

**Issue by igor-markovic** [Kukanani/vision_msgs_proposal#69]
[The wiki](http://wiki.ros.org/vision_msgs) shows `BoundingBox2DArray` as being an available message in noetic.

However, when installing `ros-noetic-vision-msgs` via apt, the message definition is missing. It looks like the [release repo](https://github.com/ros2-gbp/vision_msgs-release/branches/all?query=noetic) last updated the noetic branch in 2020, which was before the array msg [was added](https://github.com/ros-perception/vision_msgs/commit/ef04cafde553780569bb53f0d0bd3d0edc04bfc4) to the development repo.

Could the maintainer of the release repo update the noetic release to include this message?

**Comment by Kukanani** [comment]
I don't know why the documentation updated when I did not create a new release. Either way, here's the PR for the release to add the bounding box array messages. https://github.com/ros/rosdistro/pull/32721

**Comment by igor-markovic** [comment]
`BoundingBox2DArray` is now a message when installing the latest version, thanks!

**Comment by yeyanan93** [comment]
how can I solve the problem via apt inatall?

sudo apt isntall ros-noetic-vision-msgs not work.

How can I do?
