### ISSUE TITLE
BoundingBox2DArray missing for galactic

### ISSUE THREAD

**Issue by zizo1111** [Kukanani/vision_msgs_proposal#74]
Hi,

I was wondering why is BoundingBox2DArray message missing from galactic, and thus not available to install through 
```
apt-get install ros-galactic-vision-msgs
```
thanks

**Comment by Kukanani** [comment]
It was added later, and so didn't end up in every branch. Here is the recent PR for foxy: https://github.com/ros-perception/vision_msgs/pull/73. I'll forward port it to Galactic, but it won't be available in the apt version until the next release and sync.

**Comment by SteveMacenski** [comment]
Galactic is EOL
