### ISSUE TITLE
fatal error: vision_msgs/msg/detail/header__struct.hpp:

### ISSUE THREAD

**Issue by lbhwyy** [Kukanani/vision_msgs_proposal#86]
In file included from /home/tianbot/yolov5_ws/build/vision_msgs/rosidl_typesupport_cpp/vision_msgs/msg/detection2_d__type_support.cpp:7:
/home/tianbot/yolov5_ws/build/vision_msgs/rosidl_generator_cpp/vision_msgs/msg/detail/detection2_d__struct.hpp:19:10: fatal error: vision_msgs/msg/detail/header__struct.hpp: 没有那个文件或目录
   19 | #include "vision_msgs/msg/detail/header__struct.hpp"

**Comment by SteveMacenski** [comment]
That’s an odd issue. Can you try a clean build? Perhaps somethings updated on your system that made the cache invalid. 

What ros version and os? Did you update binaries recently? Can you reproduce it anywhere else?

**Comment by SteveMacenski** [comment]
Closing, no response

**Comment by jainishmehta** [comment]
HI, 
I am having a similar issue with this:
/home/jainish/ros2_ws/build/webots_ros2_msgs/rosidl_generator_cpp/webots_ros2_msgs/msg/detail/camera_recognition_object__struct.hpp:23:10: fatal error: vision_msgs/msg/detail/bounding_box2_d__struct.hpp: No such file or directory
   23 | #include "vision_msgs/msg/detail/bounding_box2_d__struct.hpp"

The other packages like geometric_msgs works fine though.
